name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'luxspy-svr/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'luxspy-svr/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/luxspy-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version if not changed
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # Check if VERSION file was changed in this commit
          if git diff --name-only HEAD~1 HEAD | grep -q "luxspy-svr/VERSION"; then
            echo "VERSION file was changed, using existing version"
          else
            echo "VERSION file was not changed, bumping patch version"
            # Read current version
            current_version=$(cat luxspy-svr/VERSION)
            # Split version into parts
            IFS='.' read -ra VERSION_PARTS <<< "$current_version"
            major="${VERSION_PARTS[0]}"
            minor="${VERSION_PARTS[1]}"
            patch="${VERSION_PARTS[2]}"
            # Increment patch version
            new_patch=$((patch + 1))
            new_version="$major.$minor.$new_patch"
            echo "Bumping version from $current_version to $new_version"
            # Update VERSION file
            echo "$new_version" > luxspy-svr/VERSION
            # Commit and push the change
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add luxspy-svr/VERSION
            git commit -m "Bump version to $new_version [skip ci]"
            git push
          fi

      - name: Read version
        id: get_version
        run: echo "VERSION=$(cat luxspy-svr/VERSION)" >> $GITHUB_ENV

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./luxspy-svr
          file: ./luxspy-svr/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT_SHA=${{ github.sha }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image info
        if: github.event_name != 'pull_request'
        run: |
          echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}" 